### PR TITLE
Jonathan Rogers Park datapoint

### PR DESCRIPTION
**Pull request by suyuhe**
My local Vancouver park recommendation.

### CODE REVIEW

**Comment by geoglrb** [comment]
Hi!

I'm sorry for all the trouble, but this pull request is doing something I haven't seen before... it says "from unknown repository" above and it seems like your (forked) repository was already deleted. Did you delete it? The typical ways to 'merge' aren't working the way I would expect, either, so that could be related. I can try to figure it out some more, or perhaps a (quick?) redo for practice? If the latter is of zero interest to you, I'll try more. Sorry again--this is strange!

**Comment by suyuhe** [comment]
Hi Luke, all good. I think I went a step too far in the instructions by deleting the fork, didn't realize that it wouldn't let the pull request go through. I can do it again. I did see that you closed this and since I'm new to GitHub I'm unsure if that's the same as deleting a comment and you don't want me to do it again?

**Comment by geoglrb** [comment]
Hi! Sorry, I closed it but I (or you, I think) can reopen it if I needed to resume working on it or if you wanted to add to that pull request. I’d appreciate you doing it again, though, yes.

**Comment by suyuhe** [comment]
I've just redone it. There appears to be a conflict - hope it works this time and let me know if you need me to fix anything else :)

**Comment by geoglrb** [comment]
Hi! Thanks so much! No, this one worked well. All is good.

The 'conflict' is almost inevitable in this particular exericse, for one of two reasons--1) most people are issuing a pull request from a branch that gets farther and farther 'behind' as I merge in other peoples' contributions, so Github can't figure out how to merge the text file itself, but I help it along; and/or 2) Github doesn't do a great job understanding the differences between two short JSON formatted files, as we have here... this causes problems with the automatic merge. I think that the latter one actually was what was going on with yours, because I think you were using an up-to-date branch when you issued the recent request? Anyway, no problem--I fix all of this behind the scenes for this exercise.

**Pull request closed without merging**
